import turtle
turtle.bgcolor("red")
square=turtle.Turtle()
square.forward(100)
square.left(90)
square.forward(100)
square.left(90)
square.forward(100)
square.left(90)
square.forward(100)
turtle.done()
